name: Docker

on:
  push:
    # Publish `main` as Docker `latest` image.
    branches:
      - main


env:
  # TODO: Change variable to your image's name.
  IMAGE_NAME: image

jobs:
  # Push image to GitHub Packages.
  # See also https://docs.docker.com/docker-hub/builds/
  push:

    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: |
          ls
          cd pager
          docker build . --file Dockerfile -t pager
          cd ../front-end
          docker build . --file Dockerfile -t frontend

      - name: Log into registry
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Push image
        run: |
          IMAGE_ID_1=${{ secrets.DOCKERHUB_USERNAME }}/pager
          IMAGE_ID_2=${{ secrets.DOCKERHUB_USERNAME }}/frontend

          # Change all uppercase to lowercase
          IMAGE_ID_1=$(echo $IMAGE_ID_1 | tr '[A-Z]' '[a-z]')
          IMAGE_ID_2=$(echo $IMAGE_ID_2 | tr '[A-Z]' '[a-z]')
          

          echo IMAGE_ID_1=$IMAGE_ID_1
          echo IMAGE_ID_2=$IMAGE_ID_2

          docker tag pager $IMAGE_ID_1:latest
          docker push $IMAGE_ID_1:latest
          
          docker tag frontend $IMAGE_ID_2:latest
          docker push $IMAGE_ID_2:latest
